### ISSUE TITLE
get_shared_slices() invalid down-cast from size_t to unsigned int

### ISSUE THREAD

**Issue by crohkohl** [GreycLab/CImg#291]
If you work with very big images the code in `get_shared_slices()` failes due to integer overflow.

```cpp
CImg<T> get_shared_slices(const unsigned int z0, const unsigned int z1, const unsigned int c0=0) {
      const unsigned int
        beg = (unsigned int)offset(0,0,z0,c0),
        end = (unsigned int)offset(0,0,z1,c0);
      if (beg>end || beg>=size() || end>=size())
        throw CImgArgumentException(_cimg_instance
                                    "get_shared_slices(): Invalid request of a shared-memory subset "
                                    "(0->%u,0->%u,%u->%u,%u).",
                                    cimg_instance,
                                    _width - 1,_height - 1,z0,z1,c0);

      return CImg<T>(_data + beg,_width,_height,z1 - z0 + 1,1,true);
    }
```

The result of the offset function should not be casted to `unsigned int`.
There might be other locations in the code where this is a problem.

**Comment by dtschump** [comment]
You are right.
This commit should fix this: https://github.com/dtschump/CImg/commit/c56548b31041d352d41fc2ed6f97b8546e5913e3

Let me know if that helps !

**Comment by crohkohl** [comment]
Works perfectly, thank you!

Am Mo., 14. Sept. 2020 um 07:56 Uhr schrieb David Tschumperlé <
notifications@github.com>:
