### ISSUE TITLE
Is this library uses RGBA32 or RGBA32 Premultiplied Or ARGB32 pixel format for 4 channel images?

### ISSUE THREAD

**Issue by 88aleksandr88** [GreycLab/CImg#375]
`QImage out = img;`
`cimg_library::CImg<uint8_t> img_c(out.bits(), out.width(), out.height(), 1, 4, false);`

img_c assumes that out.bits() in RGBA32 or RGBA32 Premultiplied format or ARGB32?

How to convert uint32_t pixel (4 bytes RGBA pixel) to cimg_library::CImg<float> or cimg_library::CImg<double> ?

**Comment by devernay** [comment]
short answer: everything is unpremultiplied here

**Comment by 88aleksandr88** [comment]
Thank you, devernay.
