### ISSUE TITLE
Is it really necessary to specify pattern?

### ISSUE THREAD

**Issue by Reptorian1125** [GreycLab/CImg#412]
Hi, after trying to draw ellipse with 1 px border in G'MIC, I'd have to wonder if it is actually necessary for the user to specify pattern. I'd like to simplify ellipse and likewise command to not need _pattern, and assume that it draws every border.

**Comment by dtschump** [comment]
Yes, command `ellipse` actually knows that you want to draw an outline rather than a filled ellipse, specifically because you specify a `pattern` parameter.
For a plain outline, just specify `0xFFFFFFFF` as the `pattern` argument.
