### ISSUE TITLE
compile error in the .h file on Visual Studio 2022

### ISSUE THREAD

**Issue by AngleaD** [GreycLab/CImg#416]
error C4146: unary minus operator applied to unsigned type, result still unsigned

original code line **34230**
  prec = precision<0 ? (unsigned int)(-siz*precision/100) : (unsigned int)precision;

my patch to remove the compilation error 
   prec = precision<0 ? (unsigned int)(siz* -precision/100) : (unsigned int)precision;

David Anglea
20 April 2024 
I have reinstalled the CIMG code on a new computer and In the years past I may have fixed this previously - but I can not recall this fact.
I down laded the zip file form GITHUB on 18 April 2024

**Comment by dtschump** [comment]
Thanks. Does that work now with the fix?
