### ISSUE TITLE
save function not overwriting existing files

### ISSUE THREAD

**Issue by BillTavis** [GreycLab/CImg#437]
Hello, I have encountered an issue in which the 'save' function will not write to disk if the file already exists. I have been using CImg for years and have never encountered this before

A complete program which replicates this error is here:
`#include "CImg.h"
using namespace cimg_library;

int main(int argc, char *argv[])
{
    char theName[] = "name.png";
    CImg<float> img(500,500,1,3);
    img.rand(0,255);
    img.save(theName);
    img.resize(100,100,1,3);
    img.save(theName);
	return 0;
}`
After running this code, there will be a 500x500 png image in the folder. The second image does not save. And if you run it again, you will notice that even the first one does not save, because the image already exists. The same thing happens if I change the extension to tiff. If I change the extension to bmp, it works as expected and a new 100x100 image is the result every time it is ran. I do have graphics magick installed so I'm not sure if that has something to do with it, but I have not been able to find a workaround for this.

**Comment by dtschump** [comment]
Did you link your code with the libtiff and libpng libraries, when compiling it ?
If not, CImg uses imagemagick or graphicsmagick as a fallback, thus I suspect there are rules defined for these programs to avoid overwriting a file.
I'll check that.

**Comment by dtschump** [comment]
Tested here on my Ubuntu 22.04 install, without defining `-Dcimg_use_png` and it overwrites the file (and it uses imagemagick for sure). Not tested with graphicsmagick though.

**Comment by BillTavis** [comment]
hello, thank you for your response!
I am compiling it with the command: 'g++ main.cpp -lpthread -lX11 -o test' 
I removed graphicsmagick and installed imagemagick on my system, and it works now! I don't actually understand what the difference is between those two, but glad to have one that works! Thank you for the fix.
For reference I am on Linux Mint 22 (Ubuntu 24.04)

**Comment by BillTavis** [comment]
Unfortunately, the problem persisted in my full program. I was also making use of libtiff there, not sure if that is it. I had already removed the program called graphicsmagick, but I wound up having to also uninstall libgraphicsmagic++ which I'm not too happy about because it means that I lost my G'MIC plugin for Gimp, but it did once again fix the problem.

I am on a brand new install of the newest Linux Mint, which is when I started encountering the problem. Any help would be appreciated. I would like to have a workaround that does not require uninstalling common libraries.

**Comment by apocelipes** [comment]
This is a CImg's bug. `save()` calls libmagick first, then imagemagick, finally graphsmagick. If one of  However CImg only checks whether file exists, does not check the exit code of the imagemagick/graphicsmagick command. That leds even if the command failed the save function will find the existed file and report the saving was success.  For your case, CImg ran imagemagick and found the already existed "name.png", so it returned, but in fact imagemagick was not found and graphicsmagick should be executed.

Check the command's exit code can fix this issue, I've sent #438 to do this. Delete the file before we overwrite on it could also solve problems but could lose performance and has TOCTOU problems.

@dtschump @BillTavis
